version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    steps:
      - checkout
      - run: make -C push-alb-stats-to-app-optics
      - store_artifacts:
          path: push-alb-stats-to-app-optics/push-alb-stats-to-app-optics.zip
          destination: push-alb-stats-to-app-optics.zip
