version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout
      - run: make -C push-alb-stats-to-app-optics test push-alb-stats-to-app-optics.zip
      - run: make -C push-athena-data-to-rds push-athena-data-to-rds.zip
      - store_artifacts:
          path: push-alb-stats-to-app-optics/push-alb-stats-to-app-optics.zip
          destination: push-alb-stats-to-app-optics.zip
      - store_artifacts:
          path: push-athena-data-to-rds/push-athena-data-to-rds.zip
          destination: push-athena-data-to-rds.zip